// domain
// export const DOMAIN = "https://c43658a3a90b.ngrok.io";
// export const DOMAIN = "https://f32531d8ff9a.ngrok.io";
export const DOMAIN = "http://localhost:3001/";

export function getIdUser(){
    return localStorage.getItem('idUser')
}


export const LIMIT = 3;
export const LIMITSANPHAM = 20;

// HTTP method 
export const HTTP_READ = "GET"
export const HTTP_CREATE = "POST"
export const HTTP_UPDATE = "PUT"
export const HTTP_DELETE = "DELETE"
// login

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE'

export const DANGKY_USER_REQUEST = 'DANGKY_USER_REQUEST'
export const DANGKY_USER_SUCCESS = 'DANGKY_USER_SUCCESS'
export const DANGKY_USER_FAILURE = 'DANGKY_USER_FAILURE'

//  San pham user

export const PAGINATION_SANPHAMUSER_REQUEST = 'PAGINATION_SANPHAMUSER_REQUEST'
export const PAGINATION_SANPHAMUSER_SUCCESS = 'PAGINATION_SANPHAMUSER_SUCCESS'
export const PAGINATION_SANPHAMUSER_FAILURE = 'PAGINATION_SANPHAMUSER_FAILURE'

export const XEMCHITIET_SANPHAM_REQUEST = 'XEMCHITIET_SANPHAM_REQUEST'
export const XEMCHITIET_SANPHAM_SUCCESS = 'XEMCHITIET_SANPHAM_SUCCESS'
export const XEMCHITIET_SANPHAM_FAILURE = 'XEMCHITIET_SANPHAM_FAILURE'

export const SEARCH_SANPHAMUSER_REQUEST = 'SEARCH_SANPHAMUSER_REQUEST'
export const SEARCH_SANPHAMUSER_SUCCESS = 'SEARCH_SANPHAMUSER_SUCCESS'
export const SEARCH_SANPHAMUSER_FAILURE = 'SEARCH_SANPHAMUSER_FAILURE'


export const ADD_GIOHANG_REQUEST = 'ADD_GIOHANG_REQUEST'
export const ADD_GIOHANG_SUCCESS = 'ADD_GIOHANG_SUCCESS'
export const ADD_GIOHANG_FAILURE = 'ADD_GIOHANG_FAILURE'

export const DELETE_GIOHANG_REQUEST = 'DELETE_GIOHANG_REQUEST'
export const DELETE_GIOHANG_SUCCESS = 'DELETE_GIOHANG_SUCCESS'
export const DELETE_GIOHANG_FAILURE = 'DELETE_GIOHANG_FAILURE'

export const THANHTOAN_GIOHANG_REQUEST = 'THANHTOAN_GIOHANG_REQUEST'
export const THANHTOAN_GIOHANG_SUCCESS = 'THANHTOAN_GIOHANG_SUCCESS'
export const THANHTOAN_GIOHANG_FAILURE = 'THANHTOAN_GIOHANG_FAILURE'

export const DATHANG_REQUEST = 'DATHANG_REQUEST'
export const DATHANG_SUCCESS = 'DATHANG_SUCCESS'
export const DATHANG_FAILURE = 'DATHANG_FAILURE'

export const PAGINATION_DONHANGUSER_REQUEST = 'PAGINATION_DONHANGUSER_REQUEST'
export const PAGINATION_DONHANGUSER_SUCCESS = 'PAGINATION_DONHANGUSER_SUCCESS'
export const PAGINATION_DONHANGUSER_FAILURE = 'PAGINATION_DONHANGUSER_FAILURE'

export const XEMCHITIET_DONHANGUSER_REQUEST = 'XEMCHITIET_DONHANGUSER_REQUEST'
export const XEMCHITIET_DONHANGUSER_SUCCESS = 'XEMCHITIET_DONHANGUSER_SUCCESS'
export const XEMCHITIET_DONHANGUSER_FAILURE = 'XEMCHITIET_DONHANGUSER_FAILURE'
// export const ADD_SANPHAM_REQUEST = 'ADD_SANPHAM_REQUEST'
// export const ADD_SANPHAM_SUCCESS = 'ADD_SANPHAM_SUCCESS'
// export const ADD_SANPHAM_FAILURE = 'ADD_SANPHAM_FAILURE'

// export const ADD_SANPHAM_REQUEST = 'ADD_SANPHAM_REQUEST'
// export const ADD_SANPHAM_SUCCESS = 'ADD_SANPHAM_SUCCESS'
// export const ADD_SANPHAM_FAILURE = 'ADD_SANPHAM_FAILURE'
// tai khoan

export const ADD_DIACHI_REQUEST = 'ADD_DIACHI_REQUEST'
export const ADD_DIACHI_SUCCESS = 'ADD_DIACHI_SUCCESS'
export const ADD_DIACHI_FAILURE = 'ADD_DIACHI_FAILURE'

export const UPDATE_DIACHI_REQUEST = 'UPDATE_DIACHI_REQUEST'
export const UPDATE_DIACHI_SUCCESS = 'UPDATE_DIACHI_SUCCESS'
export const UPDATE_DIACHI_FAILURE = 'UPDATE_DIACHI_FAILURE'

export const DELETE_DIACHI_REQUEST = 'DELETE_DIACHI_REQUEST'
export const DELETE_DIACHI_SUCCESS = 'DELETE_DIACHI_SUCCESS'
export const DELETE_DIACHI_FAILURE = 'DELETE_DIACHI_FAILURE'

// export const GET_DIACHI_REQUEST = 'GET_DIACHI_REQUEST'
// export const GET_DIACHI_SUCCESS = 'GET_DIACHI_SUCCESS'
// export const GET_DIACHI_FAILURE = 'GET_DIACHI_FAILURE'

export const GET_USER_REQUEST = 'GET_USER_REQUEST'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const GET_USER_FAILURE = 'GET_USER_FAILURE'

// export const PAGINATION_ITEM_REQUEST = 'PAGINATION_ITEM_REQUEST'
// export const PAGINATION_ITEM_SUCCESS = 'PAGINATION_ITEM_SUCCESS'
// export const PAGINATION_ITEM_FAILURE = 'PAGINATION_ITEM_FAILURE'

export const PAGINATION_SANPHAM_REQUEST = 'PAGINATION_SANPHAM_REQUEST'
export const PAGINATION_SANPHAM_SUCCESS = 'PAGINATION_SANPHAM_SUCCESS'
export const PAGINATION_SANPHAM_FAILURE = 'PAGINATION_SANPHAM_FAILURE'

export const ADD_SANPHAM_REQUEST = 'ADD_SANPHAM_REQUEST'
export const ADD_SANPHAM_SUCCESS = 'ADD_SANPHAM_SUCCESS'
export const ADD_SANPHAM_FAILURE = 'ADD_SANPHAM_FAILURE'

export const UPDATE_SANPHAM_REQUEST = 'UPDATE_SANPHAM_REQUEST'
export const UPDATE_SANPHAM_SUCCESS = 'UPDATE_SANPHAM_SUCCESS'
export const UPDATE_SANPHAM_FAILURE = 'UPDATE_SANPHAM_FAILURE'

export const DELETE_SANPHAM_REQUEST = 'DELETE_SANPHAM_REQUEST'
export const DELETE_SANPHAM_SUCCESS = 'DELETE_SANPHAM_SUCCESS'
export const DELETE_SANPHAM_FAILURE = 'DELETE_SANPHAM_FAILURE'

export const SEARCH_SANPHAM_REQUEST = 'SEARCH_SANPHAM_REQUEST'
export const SEARCH_SANPHAM_SUCCESS = 'SEARCH_SANPHAM_SUCCESS'
export const SEARCH_SANPHAM_FAILURE = 'SEARCH_SANPHAM_FAILURE'

// export const GET_HANG_REQUEST = 'GET_HANG_REQUEST'
// export const GET_HANG_SUCCESS = 'GET_HANG_SUCCESS'
// export const GET_HANG_FAILURE = 'GET_HANG_FAILURE'
// HTTP headers
export const HTTP_HEADER_JSON = {"Content-Type": "Application/json"}

// types of actions
